### ISSUE TITLE
Could you update andlib library to aar format one ?

### ISSUE THREAD

**Issue by JrmyDev** [shannah/cn1-freshdesk#3]
Since we build with gradle and Java 8 with CodenameOne, library with andlib format aren't supported anymore ... (error message when building for android).

It's noticed to use aar format instead.

Thanks .

**Comment by JrmyDev** [comment]
Up Steve. I can't build anymore for android .... But I still would like to use this library because it's a great portage !!

**Comment by JrmyDev** [comment]
Up :(

**Comment by shannah** [comment]
I have just built a release (1.1) with Chen's changes which should resolve this issue.

**Comment by gardner** [comment]
Thanks @shannah for this library! @chen-fishbein you fabulous man! Thank you!
